# Generated by Django 5.2.8 on 2025-11-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_room_town_alter_room_room_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='town',
            new_name='address',
        ),
    ]
