# Generated by Django 5.2.8 on 2025-11-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_town_room_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='amenities',
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.TextField(blank=True, verbose_name='Удобства в номере'),
        ),
    ]
