# Generated by Django 5.2.8 on 2025-12-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_booking_guest_alter_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_photo',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Фото номера'),
        ),
    ]
